numbersdict = {
    "zero": "cero",
    "one": "uno",
    "two": "dos",
    "three": "tres",
    "four": "cuatro",
    "five": "cinco",
    "six": "seis",
    "seven": "siete",
    "eight": "ocho",
    "nine": "nueve",
    "ten": "dies",
    "eleven": "once",
    "twelve": "doce",
    "thirteen": "trece",
    "fourteen": "catorce",
    "fifteen": "quince",
    "sixteen": "diesiseis",
    "seventeen": "diesisiete",
    "eighteen": "diesiocho",
    "nineteen": "diecinueve",
    "twenty": "veinte",


}